### ISSUE TITLE
Error: "identifier "cudnnConvolutionBwdFilterAlgo_t" is undefined"

### ISSUE THREAD

**Issue by karankakwani** [VisionRush/Caffe-Win32#1]
I need to build caffe for 32-bit Windows. I followed the steps given here using CUDA 6.5 and CuDNN v2. 

However, I get the following errors while building libcaffe project:-
error: identifier "cudnnConvolutionBwdFilterAlgo_t" is undefined
error: identifier "cudnnConvolutionBwdFilterPreference_t" is undefined
error: identifier "cudnnConvolutionBwdDataAlgo_t" is undefined
error: identifier "cudnnConvolutionBwdDataPreference_t" is undefined
error: identifier "cudnnConvolutionBwdFilterPreference_t" is undefined
error: identifier "cudnnConvolutionBwdFilterAlgo_t" is undefined
error: identifier "cudnnConvolutionBwdDataPreference_t" is undefined
error: identifier "cudnnConvolutionBwdDataAlgo_t" is undefined

While I found out that these errors are coming because support is only for CuDNN v3 or v4, I want to know if having caffe built using CUDA 7.5 and CuDNN v3 or v4 (as in the steps given) will make my applications work on 32-bit windows platform?

**Comment by WangJianRepo** [comment]
We have not tested yet, you can try ^_^ and please tell us the result if possible.
